apiVersion: v1
kind: Service
metadata:
  name: model-serving-backend-service
  namespace: model-serving
spec:
  selector:
    app.kubernetes.io/name: model-serving-backend
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 30000